Manejo de bases.ini  - Ahora se maneja el archivo bases.ini

diff --git a/scripts/app_set_nombre_proyecto b/scripts/app_set_nombre_proyecto
--- a/scripts/app_set_nombre_proyecto
+++ b/scripts/app_set_nombre_proyecto
@@ -6,7 +6,11 @@ DIRAPP=$DIRPROY/app
 DIRBD=$DIRPROY/bd
 ARCHIVO_NOMBRE_PROYECTO_APP="$DIRAPP/nombre_proyecto"
 ARCHIVO_NOMBRE_PROYECTO="$DIRPROY/NOMBRE_PROYECTO"
-ARCH_NOMBRE_BASEDEDATOS_AUTO="$DIRPROY/NOMBRE_BASEDEDATOS_AUTO"
+ARCH_NOMBRE_BASEDEDATOS_TOBA="$DIRPROY/NOMBRE_BASEDEDATOSTOBA"
+ARCHIVO_TOBA_BASES_INI_GENERICO="$DIRBIN/aux/bases_generico.ini"
+ARCHIVO_TOBA_BASES_INI_READY="$DIRBIN/aux/bases.ini"
+ARCHIVO_TOBA_BASES_INI_BACKUP="$DIRBIN/aux/bases_BAK.ini"
+ARCHIVO_TOBA_BASES_INI_APP="$DIRAPP/instalacion/bases.ini"
 
 if [ "$1" ];
 then
@@ -22,7 +26,11 @@ else
   fi
 fi
 
-echo $NOMBREPROYECTO > $ARCHIVO_NOMBRE_PROYECTO
+if [ -f $ARCHIVO_TOBA_BASES_INI_BACKUP ];
+then
+  echo "Error: Existe un backup en $(realpath --relative-to="$DIRPROY" $ARCHIVO_TOBA_BASES_INI_BACKUP) del archivo bases.ini, eliminelo si no lo necesita antes de continuar."
+  exit 2
+fi
 
 DOCKERCOMPOSEFILE=$DIRAPP/docker-compose.yml
 COMPOSERFILE=$DIRAPP/composer.json
@@ -33,21 +41,25 @@ COMPOSERFILE_OK=$(grep "siu-toba\/template-proyecto-toba" $COMPOSERFILE)
 if [ ! "$DOCKERCOMPOSEFILE_OK" ];
 then
   echo "Error: $(realpath --relative-to="$DIRPROY" $DOCKERCOMPOSEFILE): no contiene los placeholders necesarios para insertar el nombre. Ya estableció el nombre del proyecto?"
-  exit 2
+  exit 3
 fi
 if [ ! "$COMPOSERFILE_OK" ];
 then
   echo "Error: $(realpath --relative-to="$DIRPROY" $COMPOSERFILE) no contiene los placeholders necesarios para insertar el nombre. Ya estableció el nombre del proyecto?"
-  exit 3
+  exit 4
 fi
 
+if [ -f $ARCHIVO_TOBA_BASES_INI_APP ];
+then
+  cp $ARCHIVO_TOBA_BASES_INI_APP $ARCHIVO_TOBA_BASES_INI_BACKUP
+fi
 cp $DOCKERCOMPOSEFILE $COMPOSERFILE $DIRBIN/aux/
 
-sed -i "s/<NOMBRE\ PROYECTO>/$NOMBREPROYECTO/g" $DOCKERCOMPOSEFILE
-
-sed -n 's/.*TOBA_BASE_NOMBRE[^:]*: *\([a-zA-Z]*\)/\1/p' $DOCKERCOMPOSEFILE > $ARCH_NOMBRE_BASEDEDATOS_AUTO
+echo $NOMBREPROYECTO > $ARCHIVO_NOMBRE_PROYECTO
 
 # siu-toba/template-proyecto-toba
 sed -i "s/siu-toba\/template-proyecto-toba/$NOMBREPROYECTO/g" $COMPOSERFILE
-
+sed -i "s/<NOMBRE\ PROYECTO>/$NOMBREPROYECTO/g" $DOCKERCOMPOSEFILE
+sed -n 's/.*TOBA_BASE_NOMBRE[^:]*: *\([a-zA-Z]*\)/\1/p' $DOCKERCOMPOSEFILE > $ARCH_NOMBRE_BASEDEDATOS_TOBA
+sed "s/<NOMBRE\ PROYECTO>/$NOMBREPROYECTO/g" $ARCHIVO_TOBA_BASES_INI_GENERICO > $ARCHIVO_TOBA_BASES_INI_READY
 exit 0
diff --git a/scripts/bd_set_nombre_bd b/scripts/bd_set_nombre_bd
--- a/scripts/bd_set_nombre_bd
+++ b/scripts/bd_set_nombre_bd
@@ -5,6 +5,7 @@ DIRPROY=$DIRBIN/../
 DIRAPP=$DIRPROY/app
 DIRBD=$DIRPROY/bd
 ARCH_NOMBRE_BASEDEDATOS="$DIRPROY/NOMBRE_BASEDEDATOS"
+ARCH_NOMBRE_ESQUEMABD="$DIRPROY/NOMBRE_ESQUEMABD"
 ARCH_NOMBRE_BASEDEDATOS_AUTO="$DIRPROY/NOMBRE_BASEDEDATOS_AUTO"
 ARCH_NOMBRE_BASEDEDATOSTOBA="$DIRPROY/NOMBRE_BASEDEDATOSTOBA"
 NOMBRE_BASEDEDATOSTOBA_DEFECTO="toba_3"
@@ -30,6 +31,14 @@ else
     echo "No se puede nombrar la base de datos porque no existe el archivo '$(realpath --relative-to="$DIRPROY" $ARCH_NOMBRE_BASEDEDATOS)'"
     exit 1
   fi
+fi
+
+if [ -f $ARCH_NOMBRE_ESQUEMABD ];
+then
+  NOMBRE_ESQUEMABD=$(cat $ARCH_NOMBRE_ESQUEMABD)
+else
+  echo "No se puede nombrar la base de datos porque no existe el archivo '$(realpath --relative-to="$DIRPROY" $ARCH_NOMBRE_ESQUEMABD)'"
+  exit 2
 fi
 
 if [ -f $ARCH_NOMBRE_BASEDEDATOSTOBA ];
@@ -58,29 +67,50 @@ MSG_SIN_PLACEHOLDERS="no contiene los placeholders necesarios para insertar el n
 if [ ! "$CREARBDFILE_OK" ];
 then
   echo "Error: $(realpath --relative-to="$DIRPROY" $CREARBDFILE): $MSG_SIN_PLACEHOLDERS"
-  exit 1
+  exit 3
 fi
 if [ ! "$CREARBDTOBAFILE_SQL_OK" ];
 then
   echo "Error: $(realpath --relative-to="$DIRPROY" $CREARBDTOBAFILE_SQL): $MSG_SIN_PLACEHOLDERS"
-  exit 1
+  exit 4
 fi
 if [ ! "$RESTAURARBKBDSFILE_OK" ];
 then
   echo "Error: $(realpath --relative-to="$DIRPROY" $RESTAURARBKBDSFILE): $MSG_SIN_PLACEHOLDERS"
-  exit 1
+  exit 5
 fi
 if [ ! "$CREARBKBDSFILE_OK" ];
 then
   echo "Error: $(realpath --relative-to="$DIRPROY" $CREARBKBDSFILE): $MSG_SIN_PLACEHOLDERS"
-  exit 1
+  exit 6
+fi
+
+ARCHIVO_TOBA_BASES_INI_GENERICO="$DIRBIN/aux/bases_generico.ini"
+ARCHIVO_TOBA_BASES_INI_READY="$DIRBIN/aux/bases.ini"
+ARCHIVO_TOBA_BASES_INI_BACKUP="$DIRBIN/aux/bases_BAK.ini"
+ARCHIVO_TOBA_BASES_INI_APP="$DIRAPP/instalacion/bases.ini"
+
+if [ ! -f $ARCHIVO_TOBA_BASES_INI_READY ];
+then
+  echo "Error: No se encontró el archivo $(realpath --relative-to="$DIRPROY" $ARCHIVO_TOBA_BASES_INI_READY). Estableció el nombre del proyecto?"
+  exit 7
 fi
 
 cp $CREARBKBDSFILE $RESTAURARBKBDSFILE $CREARBDTOBAFILE_SQL $CREARBDFILE $DIRBIN/aux/
 
+if [ -f $ARCHIVO_TOBA_BASES_INI_APP ];
+then
+  cp $ARCHIVO_TOBA_BASES_INI_APP $ARCHIVO_TOBA_BASES_INI_BACKUP
+fi
+
 sed -i "s/<NOMBRE\ BASEDEDATOS>/$NOMBRE_BASEDEDATOS/g" $CREARBDFILE
+sed -i "s/<NOMBRE\ BASEDEDATOS>/$NOMBRE_BASEDEDATOS/g" $ARCHIVO_TOBA_BASES_INI_READY
+sed -i "s/<NOMBRE\ ESQUEMABD>/$NOMBRE_ESQUEMABD/g" $ARCHIVO_TOBA_BASES_INI_READY
+sed -i "s/<NOMBRE\ BASEDEDATOSTOBA>/$NOMBRE_BASEDEDATOSTOBA/g" $ARCHIVO_TOBA_BASES_INI_READY
 sed -i "s/<NOMBRE\ BASEDEDATOSTOBA>/$NOMBRE_BASEDEDATOSTOBA/g" $RESTAURARBKBDSFILE
 sed -i "s/<NOMBRE\ BASEDEDATOSTOBA>/$NOMBRE_BASEDEDATOSTOBA/g" $CREARBDTOBAFILE_SQL
 sed -i "s/<NOMBRE\ BASEDEDATOSTOBA>/$NOMBRE_BASEDEDATOSTOBA/g" $CREARBKBDSFILE
+
+cp $ARCHIVO_TOBA_BASES_INI_READY $ARCHIVO_TOBA_BASES_INI_APP
 
 exit 0
