proyecto_set_nombre: agrego argumento 1  - Argumento 1 (opcional) es el nombre del proyecto

diff --git a/scripts/app_set_nombre_proyecto b/scripts/app_set_nombre_proyecto
--- a/scripts/app_set_nombre_proyecto
+++ b/scripts/app_set_nombre_proyecto
@@ -4,40 +4,50 @@ DIRBIN=`dirname $0`
 DIRPROY=$DIRBIN/..
 DIRAPP=$DIRPROY/app
 DIRBD=$DIRPROY/bd
-ARCHIVO_NOMBRE_PROYECTO="$DIRAPP/nombre_proyecto"
+ARCHIVO_NOMBRE_PROYECTO_APP="$DIRAPP/nombre_proyecto"
+ARCHIVO_NOMBRE_PROYECTO="$DIRPROY/NOMBRE_PROYECTO"
+ARCH_NOMBRE_BASEDEDATOS_AUTO="$DIRPROY/NOMBRE_BASEDEDATOS_AUTO"
 
-if [ -f $ARCHIVO_NOMBRE_PROYECTO ];
+if [ "$1" ];
 then
-  NOMBREPROYECTO=$(cat $ARCHIVO_NOMBRE_PROYECTO)
-
-  DOCKERCOMPOSEFILE=$DIRAPP/docker-compose.yml
-  COMPOSERFILE=$DIRAPP/composer.json
-
-  DOCKERCOMPOSEFILE_OK=$(grep "<NOMBRE\ PROYECTO>" $DOCKERCOMPOSEFILE)
-  COMPOSERFILE_OK=$(grep "siu-toba\/template-proyecto-toba" $COMPOSERFILE)
-
-  if [ ! "$DOCKERCOMPOSEFILE_OK" ];
+  NOMBREPROYECTO=$1
+else
+  if [ -f $ARCHIVO_NOMBRE_PROYECTO_APP ];
   then
-    echo "Error: $DOCKERCOMPOSEFILE: no contiene los placeholders necesarios para insertar el nombre. Ya estableció el nombre del proyecto?"
+    NOMBREPROYECTO=$(cat $ARCHIVO_NOMBRE_PROYECTO_APP)
+    rm $ARCHIVO_NOMBRE_PROYECTO_APP
+  else
+    echo "No se puede nombrar el proyecto porque no existe el archivo '$(realpath --relative-to="$DIRPROY" $ARCHIVO_NOMBRE_PROYECTO_APP)' y no ha indicado el nombre de proyecto como primer argumento"
     exit 1
   fi
-  if [ ! "$COMPOSERFILE_OK" ];
-  then
-    echo "Error: $COMPOSERFILE no contiene los placeholders necesarios para insertar el nombre. Ya estableció el nombre del proyecto?"
-    exit 1
-  fi
-
-  cp $DOCKERCOMPOSEFILE $COMPOSERFILE $DIRBIN/aux/
-
-  sed -i "s/<NOMBRE\ PROYECTO>/$NOMBREPROYECTO/g" $DOCKERCOMPOSEFILE
-
-  # siu-toba/template-proyecto-toba
-  sed -i "s/siu-toba\/template-proyecto-toba/$NOMBREPROYECTO/g" $COMPOSERFILE
-
-  rm $ARCHIVO_NOMBRE_PROYECTO
-
-  exit 0
 fi
 
-echo "No se puede nombrar el proyecto porque no existe el archivo '$ARCHIVO_NOMBRE_PROYECTO'"
-exit 1
+echo $NOMBREPROYECTO > $ARCHIVO_NOMBRE_PROYECTO
+
+DOCKERCOMPOSEFILE=$DIRAPP/docker-compose.yml
+COMPOSERFILE=$DIRAPP/composer.json
+
+DOCKERCOMPOSEFILE_OK=$(grep "<NOMBRE\ PROYECTO>" $DOCKERCOMPOSEFILE)
+COMPOSERFILE_OK=$(grep "siu-toba\/template-proyecto-toba" $COMPOSERFILE)
+
+if [ ! "$DOCKERCOMPOSEFILE_OK" ];
+then
+  echo "Error: $(realpath --relative-to="$DIRPROY" $DOCKERCOMPOSEFILE): no contiene los placeholders necesarios para insertar el nombre. Ya estableció el nombre del proyecto?"
+  exit 2
+fi
+if [ ! "$COMPOSERFILE_OK" ];
+then
+  echo "Error: $(realpath --relative-to="$DIRPROY" $COMPOSERFILE) no contiene los placeholders necesarios para insertar el nombre. Ya estableció el nombre del proyecto?"
+  exit 3
+fi
+
+cp $DOCKERCOMPOSEFILE $COMPOSERFILE $DIRBIN/aux/
+
+sed -i "s/<NOMBRE\ PROYECTO>/$NOMBREPROYECTO/g" $DOCKERCOMPOSEFILE
+
+sed -n 's/.*TOBA_BASE_NOMBRE[^:]*: *\([a-zA-Z]*\)/\1/p' $DOCKERCOMPOSEFILE > $ARCH_NOMBRE_BASEDEDATOS_AUTO
+
+# siu-toba/template-proyecto-toba
+sed -i "s/siu-toba\/template-proyecto-toba/$NOMBREPROYECTO/g" $COMPOSERFILE
+
+exit 0
diff --git a/scripts/bd_set_nombre_bd b/scripts/bd_set_nombre_bd
--- a/scripts/bd_set_nombre_bd
+++ b/scripts/bd_set_nombre_bd
@@ -5,66 +5,82 @@ DIRPROY=$DIRBIN/../
 DIRAPP=$DIRPROY/app
 DIRBD=$DIRPROY/bd
 ARCH_NOMBRE_BASEDEDATOS="$DIRPROY/NOMBRE_BASEDEDATOS"
+ARCH_NOMBRE_BASEDEDATOS_AUTO="$DIRPROY/NOMBRE_BASEDEDATOS_AUTO"
 ARCH_NOMBRE_BASEDEDATOSTOBA="$DIRPROY/NOMBRE_BASEDEDATOSTOBA"
 NOMBRE_BASEDEDATOSTOBA_DEFECTO="toba_3"
 
 if [ -f $ARCH_NOMBRE_BASEDEDATOS ];
 then
   NOMBRE_BASEDEDATOS=$(cat $ARCH_NOMBRE_BASEDEDATOS)
-
-  if [ -f $ARCH_NOMBRE_BASEDEDATOSTOBA ];
+  if [ -f $ARCH_NOMBRE_BASEDEDATOS_AUTO ];
   then
-    NOMBRE_BASEDEDATOSTOBA=$(cat $ARCH_NOMBRE_BASEDEDATOSTOBA)
+    rm $ARCH_NOMBRE_BASEDEDATOS_AUTO
+  fi
+else
+  if [ -f $ARCH_NOMBRE_BASEDEDATOS_AUTO ];
+  then
+    NOMBRE_BASEDEDATOS=$(cat $ARCH_NOMBRE_BASEDEDATOS_AUTO)
+
+    echo ""
+    echo "Creando $(realpath --relative-to="$DIRPROY" $ARCH_NOMBRE_BASEDEDATOS)..."
+    echo $NOMBRE_BASEDEDATOS > $ARCH_NOMBRE_BASEDEDATOS
+    rm $ARCH_NOMBRE_BASEDEDATOS_AUTO
+    echo "...echo."
   else
-    NOMBRE_BASEDEDATOSTOBA=$NOMBRE_BASEDEDATOSTOBA_DEFECTO
-
-    echo ""
-    echo "Advertencia: no existe el archivo '$ARCH_NOMBRE_BASEDEDATOSTOBA':"
-    echo " Como nombre de la base de datos de toba se usa: $NOMBRE_BASEDEDATOSTOBA_DEFECTO"
-    echo ""
-  fi
-
-  CREARBDFILE=$DIRBD/bd_app_crear.sql
-  CREARBDTOBAFILE_SQL=$DIRBD/bd_toba_crear.sql
-  RESTAURARBKBDSFILE=$DIRBD/bds_backup_restaurar.sh
-  CREARBKBDSFILE=$DIRBD/bds_backup_crear.sh
-
-  CREARBDFILE_OK=$(grep "<NOMBRE\ BASEDEDATOS>" $CREARBDFILE)
-  CREARBDTOBAFILE_SQL_OK=$(grep "<NOMBRE\ BASEDEDATOSTOBA>" $CREARBDTOBAFILE_SQL)
-  RESTAURARBKBDSFILE_OK=$(grep "<NOMBRE\ BASEDEDATOSTOBA>" $RESTAURARBKBDSFILE)
-  CREARBKBDSFILE_OK=$(grep "<NOMBRE\ BASEDEDATOSTOBA>" $CREARBKBDSFILE)
-
-  MSG_SIN_PLACEHOLDERS="no contiene los placeholders necesarios para insertar el nombre. Ya estableció el nombre del proyecto?"
-  if [ ! "$CREARBDFILE_OK" ];
-  then
-    echo "Error: $CREARBDFILE: $MSG_SIN_PLACEHOLDERS"
+    echo "No se puede nombrar la base de datos porque no existe el archivo '$(realpath --relative-to="$DIRPROY" $ARCH_NOMBRE_BASEDEDATOS)'"
     exit 1
   fi
-  if [ ! "$CREARBDTOBAFILE_SQL_OK" ];
-  then
-    echo "Error: $CREARBDTOBAFILE_SQL: $MSG_SIN_PLACEHOLDERS"
-    exit 1
-  fi
-  if [ ! "$RESTAURARBKBDSFILE_OK" ];
-  then
-    echo "Error: $RESTAURARBKBDSFILE: $MSG_SIN_PLACEHOLDERS"
-    exit 1
-  fi
-  if [ ! "$CREARBKBDSFILE_OK" ];
-  then
-    echo "Error: $CREARBKBDSFILE: $MSG_SIN_PLACEHOLDERS"
-    exit 1
-  fi
-
-  cp $CREARBKBDSFILE $RESTAURARBKBDSFILE $CREARBDTOBAFILE_SQL $CREARBDFILE $DIRBIN/aux/
-
-  sed -i "s/<NOMBRE\ BASEDEDATOS>/$NOMBRE_BASEDEDATOS/g" $CREARBDFILE
-  sed -i "s/<NOMBRE\ BASEDEDATOSTOBA>/$NOMBRE_BASEDEDATOSTOBA/g" $RESTAURARBKBDSFILE
-  sed -i "s/<NOMBRE\ BASEDEDATOSTOBA>/$NOMBRE_BASEDEDATOSTOBA/g" $CREARBDTOBAFILE_SQL
-  sed -i "s/<NOMBRE\ BASEDEDATOSTOBA>/$NOMBRE_BASEDEDATOSTOBA/g" $CREARBKBDSFILE
-
-  exit 0
 fi
 
-echo "No se puede nombrar la base de datos porque no existe el archivo '$ARCH_NOMBRE_BASEDEDATOS'"
-exit 1
+if [ -f $ARCH_NOMBRE_BASEDEDATOSTOBA ];
+then
+  NOMBRE_BASEDEDATOSTOBA=$(cat $ARCH_NOMBRE_BASEDEDATOSTOBA)
+else
+  NOMBRE_BASEDEDATOSTOBA=$NOMBRE_BASEDEDATOSTOBA_DEFECTO
+
+  echo ""
+  echo "Advertencia: no existe el archivo '$(realpath --relative-to="$DIRPROY" $ARCH_NOMBRE_BASEDEDATOSTOBA)':"
+  echo " Como nombre de la base de datos de toba se usa: $(realpath --relative-to="$DIRPROY" $NOMBRE_BASEDEDATOSTOBA_DEFECTO)"
+  echo ""
+fi
+
+CREARBDFILE=$DIRBD/bd_app_crear.sql
+CREARBDTOBAFILE_SQL=$DIRBD/bd_toba_crear.sql
+RESTAURARBKBDSFILE=$DIRBD/bds_backup_restaurar.sh
+CREARBKBDSFILE=$DIRBD/bds_backup_crear.sh
+
+CREARBDFILE_OK=$(grep "<NOMBRE\ BASEDEDATOS>" $CREARBDFILE)
+CREARBDTOBAFILE_SQL_OK=$(grep "<NOMBRE\ BASEDEDATOSTOBA>" $CREARBDTOBAFILE_SQL)
+RESTAURARBKBDSFILE_OK=$(grep "<NOMBRE\ BASEDEDATOSTOBA>" $RESTAURARBKBDSFILE)
+CREARBKBDSFILE_OK=$(grep "<NOMBRE\ BASEDEDATOSTOBA>" $CREARBKBDSFILE)
+
+MSG_SIN_PLACEHOLDERS="no contiene los placeholders necesarios para insertar el nombre. Ya estableció el nombre del proyecto?"
+if [ ! "$CREARBDFILE_OK" ];
+then
+  echo "Error: $(realpath --relative-to="$DIRPROY" $CREARBDFILE): $MSG_SIN_PLACEHOLDERS"
+  exit 1
+fi
+if [ ! "$CREARBDTOBAFILE_SQL_OK" ];
+then
+  echo "Error: $(realpath --relative-to="$DIRPROY" $CREARBDTOBAFILE_SQL): $MSG_SIN_PLACEHOLDERS"
+  exit 1
+fi
+if [ ! "$RESTAURARBKBDSFILE_OK" ];
+then
+  echo "Error: $(realpath --relative-to="$DIRPROY" $RESTAURARBKBDSFILE): $MSG_SIN_PLACEHOLDERS"
+  exit 1
+fi
+if [ ! "$CREARBKBDSFILE_OK" ];
+then
+  echo "Error: $(realpath --relative-to="$DIRPROY" $CREARBKBDSFILE): $MSG_SIN_PLACEHOLDERS"
+  exit 1
+fi
+
+cp $CREARBKBDSFILE $RESTAURARBKBDSFILE $CREARBDTOBAFILE_SQL $CREARBDFILE $DIRBIN/aux/
+
+sed -i "s/<NOMBRE\ BASEDEDATOS>/$NOMBRE_BASEDEDATOS/g" $CREARBDFILE
+sed -i "s/<NOMBRE\ BASEDEDATOSTOBA>/$NOMBRE_BASEDEDATOSTOBA/g" $RESTAURARBKBDSFILE
+sed -i "s/<NOMBRE\ BASEDEDATOSTOBA>/$NOMBRE_BASEDEDATOSTOBA/g" $CREARBDTOBAFILE_SQL
+sed -i "s/<NOMBRE\ BASEDEDATOSTOBA>/$NOMBRE_BASEDEDATOSTOBA/g" $CREARBKBDSFILE
+
+exit 0
