scripts y bd: helpers varios y simplificaciones

diff --git a/scripts/bd_set_nombre_bd b/scripts/bd_set_nombre_bd
--- a/scripts/bd_set_nombre_bd
+++ b/scripts/bd_set_nombre_bd
@@ -10,6 +10,10 @@ ARCH_NOMBRE_BASEDEDATOS_AUTO="$DIRPROY/NOMBRE_BASEDEDATOS_AUTO"
 ARCH_NOMBRE_BASEDEDATOSTOBA="$DIRPROY/NOMBRE_BASEDEDATOSTOBA"
 NOMBRE_BASEDEDATOSTOBA_DEFECTO="toba_3"
 
+PLACEHOLDER_NOMBREBASE="<NOMBRE\ BASEDEDATOS>"
+PLACEHOLDER_NOMBREESQUEMA="<NOMBRE\ ESQUEMABD>"
+PLACEHOLDER_NOMBREBASETOBA="<NOMBRE\ BASEDEDATOSTOBA>"
+
 if [ -f $ARCH_NOMBRE_BASEDEDATOS ];
 then
   NOMBRE_BASEDEDATOS=$(cat $ARCH_NOMBRE_BASEDEDATOS)
@@ -54,14 +58,26 @@ else
 fi
 
 CREARBDFILE=$DIRBD/bd_app_crear.sql
+CREARSCHFILE=$DIRBD/bd_app_crear_esquema.sql
 CREARBDTOBAFILE_SQL=$DIRBD/bd_toba_crear.sql
-RESTAURARBKBDSFILE=$DIRBD/bds_backup_restaurar.sh
-CREARBKBDSFILE=$DIRBD/bds_backup_crear.sh
+MSG_404_FILE="No se encontró el archivo"
 
-CREARBDFILE_OK=$(grep "<NOMBRE\ BASEDEDATOS>" $CREARBDFILE)
-CREARBDTOBAFILE_SQL_OK=$(grep "<NOMBRE\ BASEDEDATOSTOBA>" $CREARBDTOBAFILE_SQL)
-RESTAURARBKBDSFILE_OK=$(grep "<NOMBRE\ BASEDEDATOSTOBA>" $RESTAURARBKBDSFILE)
-CREARBKBDSFILE_OK=$(grep "<NOMBRE\ BASEDEDATOSTOBA>" $CREARBKBDSFILE)
+if [ ! -f $CREARBDFILE ]; then
+	echo "Error: $(realpath --relative-to="$DIRPROY" $CREARBDFILE): $MSG_404_FILE"
+  exit 3
+fi
+if [ ! -f $CREARSCHFILE ]; then
+	echo "Error: $(realpath --relative-to="$DIRPROY" $CREARSCHFILE): $MSG_404_FILE"
+  exit 3
+fi
+if [ ! -f $CREARBDTOBAFILE_SQL ]; then
+	echo "Error: $(realpath --relative-to="$DIRPROY" $CREARBDTOBAFILE_SQL): $MSG_404_FILE"
+  exit 3
+fi
+
+CREARBDFILE_OK=$(grep "$PLACEHOLDER_NOMBREBASE" $CREARBDFILE)
+CREARSCHFILE_OK=$(grep "$PLACEHOLDER_NOMBREESQUEMA" $CREARSCHFILE)
+CREARBDTOBAFILE_SQL_OK=$(grep "$PLACEHOLDER_NOMBREBASETOBA" $CREARBDTOBAFILE_SQL)
 
 MSG_SIN_PLACEHOLDERS="no contiene los placeholders necesarios para insertar el nombre. Ya estableció el nombre del proyecto?"
 if [ ! "$CREARBDFILE_OK" ];
@@ -69,20 +85,15 @@ then
   echo "Error: $(realpath --relative-to="$DIRPROY" $CREARBDFILE): $MSG_SIN_PLACEHOLDERS"
   exit 3
 fi
+if [ ! "$CREARSCHFILE_OK" ];
+then
+  echo "Error: $(realpath --relative-to="$DIRPROY" $CREARSCHFILE): $MSG_SIN_PLACEHOLDERS"
+  exit 3
+fi
 if [ ! "$CREARBDTOBAFILE_SQL_OK" ];
 then
   echo "Error: $(realpath --relative-to="$DIRPROY" $CREARBDTOBAFILE_SQL): $MSG_SIN_PLACEHOLDERS"
   exit 4
-fi
-if [ ! "$RESTAURARBKBDSFILE_OK" ];
-then
-  echo "Error: $(realpath --relative-to="$DIRPROY" $RESTAURARBKBDSFILE): $MSG_SIN_PLACEHOLDERS"
-  exit 5
-fi
-if [ ! "$CREARBKBDSFILE_OK" ];
-then
-  echo "Error: $(realpath --relative-to="$DIRPROY" $CREARBKBDSFILE): $MSG_SIN_PLACEHOLDERS"
-  exit 6
 fi
 
 ARCHIVO_TOBA_BASES_INI_GENERICO="$DIRBIN/aux/bases_generico.ini"
@@ -96,20 +107,19 @@ then
   exit 7
 fi
 
-cp $CREARBKBDSFILE $RESTAURARBKBDSFILE $CREARBDTOBAFILE_SQL $CREARBDFILE $DIRBIN/aux/
+cp $CREARBDTOBAFILE_SQL $CREARBDFILE $CREARSCHFILE $DIRBIN/aux/
 
 if [ -f $ARCHIVO_TOBA_BASES_INI_APP ];
 then
   cp $ARCHIVO_TOBA_BASES_INI_APP $ARCHIVO_TOBA_BASES_INI_BACKUP
 fi
 
-sed -i "s/<NOMBRE\ BASEDEDATOS>/$NOMBRE_BASEDEDATOS/g" $CREARBDFILE
-sed -i "s/<NOMBRE\ BASEDEDATOS>/$NOMBRE_BASEDEDATOS/g" $ARCHIVO_TOBA_BASES_INI_READY
-sed -i "s/<NOMBRE\ ESQUEMABD>/$NOMBRE_ESQUEMABD/g" $ARCHIVO_TOBA_BASES_INI_READY
-sed -i "s/<NOMBRE\ BASEDEDATOSTOBA>/$NOMBRE_BASEDEDATOSTOBA/g" $ARCHIVO_TOBA_BASES_INI_READY
-sed -i "s/<NOMBRE\ BASEDEDATOSTOBA>/$NOMBRE_BASEDEDATOSTOBA/g" $RESTAURARBKBDSFILE
-sed -i "s/<NOMBRE\ BASEDEDATOSTOBA>/$NOMBRE_BASEDEDATOSTOBA/g" $CREARBDTOBAFILE_SQL
-sed -i "s/<NOMBRE\ BASEDEDATOSTOBA>/$NOMBRE_BASEDEDATOSTOBA/g" $CREARBKBDSFILE
+sed -i "s/$PLACEHOLDER_NOMBREBASE/$NOMBRE_BASEDEDATOS/g" $CREARBDFILE
+sed -i "s/$PLACEHOLDER_NOMBREESQUEMA/$NOMBRE_ESQUEMABD/g" $CREARSCHFILE
+sed -i "s/$PLACEHOLDER_NOMBREBASE/$NOMBRE_BASEDEDATOS/g" $ARCHIVO_TOBA_BASES_INI_READY
+sed -i "s/$PLACEHOLDER_NOMBREESQUEMA/$NOMBRE_ESQUEMABD/g" $ARCHIVO_TOBA_BASES_INI_READY
+sed -i "s/$PLACEHOLDER_NOMBREBASETOBA/$NOMBRE_BASEDEDATOSTOBA/g" $ARCHIVO_TOBA_BASES_INI_READY
+sed -i "s/$PLACEHOLDER_NOMBREBASETOBA/$NOMBRE_BASEDEDATOSTOBA/g" $CREARBDTOBAFILE_SQL
 
 cp $ARCHIVO_TOBA_BASES_INI_READY $ARCHIVO_TOBA_BASES_INI_APP
 
diff --git a/scripts/proyecto_isset_nombre b/scripts/proyecto_isset_nombre
--- a/scripts/proyecto_isset_nombre
+++ b/scripts/proyecto_isset_nombre
@@ -1,9 +1,13 @@
 #!/usr/bin/env bash
 
-DIRBIN=`dirname $0`
+DIRBIN=$(dirname $0)
 DIRPROY=$DIRBIN/..
 DIRAPP=$DIRPROY/app
 DIRBD=$DIRPROY/bd
+
+PLACEHOLDER_NOMBREBASE="<NOMBRE\ BASEDEDATOS>"
+PLACEHOLDER_NOMBREESQUEMA="<NOMBRE\ ESQUEMABD>"
+PLACEHOLDER_NOMBREBASETOBA="<NOMBRE\ BASEDEDATOSTOBA>"
 
 # APP
   DOCKERCOMPOSEFILE=$DIRAPP/docker-compose.yml
@@ -26,14 +30,12 @@ DIRBD=$DIRPROY/bd
 
 # BD
   CREARBDFILE=$DIRBD/bd_app_crear.sql
+	CREARSCHFILE=$DIRBD/bd_app_crear_esquema.sql
   CREARBDTOBAFILE_SQL=$DIRBD/bd_toba_crear.sql
-  RESTAURARBKBDSFILE=$DIRBD/bds_backup_restaurar.sh
-  CREARBKBDSFILE=$DIRBD/bds_backup_crear.sh
 
-  CREARBDFILE_OK=$(grep "<NOMBRE\ BASEDEDATOS>" $CREARBDFILE)
-  CREARBDTOBAFILE_SQL_OK=$(grep "<NOMBRE\ BASEDEDATOSTOBA>" $CREARBDTOBAFILE_SQL)
-  RESTAURARBKBDSFILE_OK=$(grep "<NOMBRE\ BASEDEDATOSTOBA>" $RESTAURARBKBDSFILE)
-  CREARBKBDSFILE_OK=$(grep "<NOMBRE\ BASEDEDATOSTOBA>" $CREARBKBDSFILE)
+	CREARBDFILE_OK=$(grep "$PLACEHOLDER_NOMBREBASE" $CREARBDFILE)
+	CREARSCHFILE_OK=$(grep "$PLACEHOLDER_NOMBREESQUEMA" $CREARSCHFILE)
+  CREARBDTOBAFILE_SQL_OK=$(grep "$PLACEHOLDER_NOMBREBASETOBA" $CREARBDTOBAFILE_SQL)
 
   MSG_SIN_PLACEHOLDERS="contiene los placeholders necesarios para insertar el nombre. Ya estableció el nombre del proyecto?"
   if [ "$CREARBDFILE_OK" ];
@@ -41,19 +43,14 @@ DIRBD=$DIRPROY/bd
     echo "Error en $CREARBDFILE: $MSG_SIN_PLACEHOLDERS"
     exit 1
   fi
+  if [ "$CREARSCHFILE_OK" ];
+  then
+    echo "Error en $CREARSCHFILE: $MSG_SIN_PLACEHOLDERS"
+    exit 1
+  fi
   if [ "$CREARBDTOBAFILE_SQL_OK" ];
   then
     echo "Error en $CREARBDTOBAFILE_SQL: $MSG_SIN_PLACEHOLDERS"
-    exit 1
-  fi
-  if [ "$RESTAURARBKBDSFILE_OK" ];
-  then
-    echo "Error en $RESTAURARBKBDSFILE: $MSG_SIN_PLACEHOLDERS"
-    exit 1
-  fi
-  if [ "$CREARBKBDSFILE_OK" ];
-  then
-    echo "Error en $CREARBKBDSFILE: $MSG_SIN_PLACEHOLDERS"
     exit 1
   fi
 
